package network.warzone.mars.api.http

enum class ApiExceptionType(val code: String) {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    SESSION_INACTIVE("SESSION_INACTIVE"),
    PLAYER_MISSING("PLAYER_MISSING"),
    RANK_CONFLICT("RANK_CONFLICT"),
    RANK_MISSING("RANK_MISSING"),
    RANK_ALREADY_PRESENT("RANK_ALREADY_PRESENT"),
    RANK_NOT_PRESENT("RANK_NOT_PRESENT"),
    TAG_CONFLICT("TAG_CONFLICT"),
    TAG_MISSING("TAG_MISSING"),
    TAG_ALREADY_PRESENT("TAG_ALREADY_PRESENT"),
    TAG_NOT_PRESENT("TAG_NOT_PRESENT"),
    MAP_MISSING("MAP_MISSING"),
    PUNISHMENT_MISSING("PUNISHMENT_MISSING");
}