package network.warzone.mars.api.http

enum class ApiExceptionType {
    INTERNAL_SERVER_ERROR,
    ACHIEVEMENT_CONFLICT,
    VALIDATION_ERROR,
    SESSION_INACTIVE,
    PLAYER_MISSING,
    RANK_CONFLICT,
    RANK_MISSING,
    RANK_ALREADY_PRESENT,
    RANK_NOT_PRESENT,
    TAG_CONFLICT,
    TAG_MISSING,
    TAG_ALREADY_PRESENT,
    TAG_NOT_PRESENT,
    MAP_MISSING,
    PUNISHMENT_MISSING,
    PUNISHMENT_ALREADY_REVERTED,
    NOTE_MISSING
}