name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
        cache: gradle
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mars
        path: build/libs/Mars-1.0-SNAPSHOT-all.jar